log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://orders:orders@orders_db/orders?sslmode=disable"

listener:
  addr: :8000

chains:
  url: "http://swapica"

notifications:
  push_url: ""
  channel_address: ""
  push_comm_address: ""
  private_key: ""

cop:
  disabled: true
  endpoint: "http://cop"
  upstream: "http://order-aggregator"
  service_name: order-aggregator-svc
  service_prefix: "integrations/order-aggregator"
  service_port: 80
